language: java

jdk:
-openjdk11

move back to dist: trusty

addons:
  sonarcloud:
    organization: "Emptyiles3-github"

sudo: false # faster builds

install:
-eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
script: 
-"mvn cobertura:cobertura"
- sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
